version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=your_app_key
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 06102024-bwpss
      MYSQL_ROOT_PASSWORD: 06102024-bwpss-root
      MYSQL_USER: 06102024-bwpss
      MYSQL_PASSWORD: 06102024-bwpss
